#!/bin/sh
set -e
export ANSIBLE_STDOUT_CALLBACK=yaml

if [ "$ANSIBLE" = "true" ]; then
  if [ "$ANSIBLE_PULL" = "true" ]; then
    echo "Pulling and running latest server config ansible playbook"

    git config --global --add safe.directory /server-config

    ansible-pull -U "https://${GITHUB_TOKEN}@github.com/Gensokyo-Reimagined/gensou-config.git" -d "/server-config" --checkout "${ANSIBLE_PULL_BRANCH:=main}"
  elif [ -f "/server-config/local.yml" ]; then
    echo "Running local server config ansible playbook"

    ansible-playbook /gensou-config/local.yml --extra-vars "server_name=$SERVER_NAME dest=/data"
  fi
else
  echo "ANSIBLE not set to 'true', not running playbook"
fi
